# Generated by Django 5.1.4 on 2024-12-06 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'doc_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('termid', models.AutoField(db_column='termid', primary_key=True, serialize=False)),
                ('term', models.CharField(db_column='term', max_length=255)),
            ],
            options={
                'db_table': 'term_dict',
            },
        ),
        migrations.CreateModel(
            name='InvertedIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.IntegerField()),
                ('tf_idf', models.FloatField()),
                ('positions', models.TextField()),
                ('docid', models.ForeignKey(db_column='docid', on_delete=django.db.models.deletion.CASCADE, related_name='inverted_indices', to='search.document')),
                ('termid', models.ForeignKey(db_column='termid', on_delete=django.db.models.deletion.CASCADE, related_name='inverted_indices', to='search.term')),
            ],
            options={
                'db_table': 'inverted_index',
            },
        ),
    ]
